runtime: python
instance_class: B1
env: flex
entrypoint: gunicorn -b :$Port main:app

runtime_config:
  python_version: 3

handlers:
 - url: '/.*'
   script: auto

readiness_check:
  path: '/readiness_check'
  check_interval_sec: 20
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
  
liveness_check:
  path: '/liveness_check'
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 2
  initial_delay_sec: 300

