runtime: python
env: flex
entrypoiny: gunicorn -b :$Port main:server

runtime_config:
  python_version: 3

instance_class: F2

handlers:
- url: /.*
  script: auto
  login: admin
  auth_fail_action: redirect

manual_scaling: 
  instances: 1

resources:
  cpu: 0.2
  memory_gb: 0.5
  disk_size_gb: 10


